// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
require("./fonts.css");

module.exports.headingLarge = {
  fontFamily: "Whyte",
  fontSize: "32px",
  fontWeight: 700,
  fontStyle: "normal",
  lineHeight: "48px",
};
module.exports.heading = {
  fontFamily: "Inter",
  fontSize: "18px",
  fontWeight: 600,
  fontStyle: "normal",
  lineHeight: "26px",
};
module.exports.headingSmall = {
  fontFamily: "Whyte",
  fontSize: "16px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "20px",
};
module.exports.body = {
  fontFamily: "Whyte",
  fontSize: "14px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "20px",
};
module.exports.label = {
  fontFamily: "Whyte",
  fontSize: "16px",
  fontWeight: 700,
  fontStyle: "normal",
  lineHeight: "20px",
};
module.exports.labelSmall = {
  fontFamily: "Whyte",
  fontSize: "12px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "16px",
};
