// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
require("./fonts.css");

export const heading = {
  fontFamily: "Visly Roboto",
  fontSize: "20px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "26px",
};
export const headingLarge = {
  fontFamily: "Visly Roboto",
  fontSize: "32px",
  fontWeight: 700,
  fontStyle: "normal",
  lineHeight: "48px",
};
export const headingSmall = {
  fontFamily: "Visly Roboto",
  fontSize: "16px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "20px",
};
export const label = {
  fontFamily: "Visly Roboto",
  fontSize: "16px",
  fontWeight: 700,
  fontStyle: "normal",
  lineHeight: "20px",
};
export const labelSmall = {
  fontFamily: "Visly Roboto",
  fontSize: "12px",
  fontWeight: 400,
  fontStyle: "normal",
  lineHeight: "16px",
};
