// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export interface TextStyle {
  fontFamily: string;
  fontSize: string;
  fontWeight: number;
  fontStyle: string;
  lineHeight?: string;
}
export const heading: TextStyle;
export const headingLarge: TextStyle;
export const headingSmall: TextStyle;
export const label: TextStyle;
export const labelSmall: TextStyle;
