// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const success = "rgba(46,204,113,1)";
export const successDark = "rgba(39,174,96,1)";
export const danger = "rgba(238,0,0,1)";
export const dangerDark = "rgba(204,0,0,1)";
export const dangerLight = "rgba(255,26,26,1)";
export const purple = "rgba(123,97,255,1)";
export const purpleLight = "rgba(166,148,255,1)";
export const purpleDark = "rgba(81,46,255,1)";
export const yellow = "rgba(255,235,0,1)";
export const green = "rgba(27,196,125,1)";
export const red = "rgba(242,72,34,1)";
export const vislyWhite = "rgba(255,255,255,1)";
export const vislyBlack = "rgba(0,0,0,1)";
export const vislyBlue = "rgba(0,112,243,1)";
export const vislyBlueDark = "rgba(3,102,214,1)";
export const vislyGrayLight = "rgba(240,240,240,1)";
export const vislyGray = "rgba(229,229,229,1)";
export const vislyGrayDark = "rgba(197,197,197,1)";
export const vislyBlueLight = "rgba(50,145,255,1)";
