// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const success: string;
export const successDark: string;
export const danger: string;
export const dangerDark: string;
export const dangerLight: string;
export const purple: string;
export const purpleLight: string;
export const purpleDark: string;
export const yellow: string;
export const green: string;
export const red: string;
export const vislyWhite: string;
export const vislyBlack: string;
export const vislyBlue: string;
export const vislyBlueDark: string;
export const vislyGrayLight: string;
export const vislyGray: string;
export const vislyGrayDark: string;
export const vislyBlueLight: string;
