// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const light: string;
export const dark: string;
export const success: string;
export const successDark: string;
export const accent: string;
export const accentDark: string;
export const danger: string;
export const dangerDark: string;
export const grayLight: string;
export const gray: string;
export const grayDark: string;
export const accentLight: string;
export const dangerLight: string;
export const purple: string;
export const purpleLight: string;
export const purpleDark: string;
export const yellow: string;
export const green: string;
export const red: string;
