// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const backgroundGray = "rgba(247,248,250,1)";
export const baseDark = "rgba(80,80,80,1)";
export const baseDisabled = "rgba(197,197,197,1)";
export const danger = "rgba(238,0,0,1)";
export const dangerDark = "rgba(204,0,0,1)";
export const dangerLight = "rgba(255,26,26,1)";
export const focusHighlight = "rgba(124,114,220,1)";
export const green = "rgba(27,196,125,1)";
export const grey = "rgba(218,218,218,1)";
export const purple = "rgba(124,114,220,1)";
export const purpleLight = "rgba(166,148,255,1)";
export const red = "rgba(242,72,34,1)";
export const success = "rgba(46,204,113,1)";
export const successDark = "rgba(39,174,96,1)";
export const white = "rgba(255,255,255,1)";
export const yellow = "rgba(255,235,0,1)";
