// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const backgroundGray: string;
export const baseDark: string;
export const baseDisabled: string;
export const danger: string;
export const dangerDark: string;
export const dangerLight: string;
export const focusHighlight: string;
export const green: string;
export const grey: string;
export const purple: string;
export const purpleLight: string;
export const red: string;
export const success: string;
export const successDark: string;
export const white: string;
export const yellow: string;
