// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import React, {
  createContext,
  useContext,
  useRef,
  useState,
  useLayoutEffect,
} from "react";
import {
  mergeProps,
  HiddenSelect,
  useSelectState,
  useSelect,
  useButton,
  useListBox,
  useOption,
  DismissButton,
  useFocusRing,
} from "@visly/core";
import { combineRef, exists, renderChildren } from "./_internal_utils";
import { usePrimitive } from "./_internal_usePrimitive";
import { Popover } from "./_internal_popover";
import {
  CollectionRoot,
  proxy,
  CollectionItemProxy,
  ItemContext,
} from "./_internal_collection";
export const SelectContext = createContext({
  triggerProps: {},
  triggerRef: null,
  buttonStyles: {},
  testId: "",
  vislyProps: {},
  menuProps: {},
  state: null,
  renderInline: false,
  rootClassName: "",
  triggerMeasureRef: null,
});

function SelectButtonImpl(props) {
  const {
    triggerRef,
    triggerMeasureRef,
    vislyProps,
    testId,
    buttonStyles,
    triggerProps,
  } = useContext(SelectContext);

  const _triggerProps = mergeProps(triggerProps, {
    onKeyDown: (e) => {
      if (e.key === "Escape") {
        e.continuePropagation();
      }
    },
  });

  const { buttonProps } = useButton(_triggerProps, triggerRef);
  return (
    <button
      {...mergeProps(buttonProps, vislyProps)}
      data-testid={testId}
      ref={combineRef(
        combineRef(props.measureRef, triggerMeasureRef),
        triggerRef
      )}
      className={props.className}
      style={buttonStyles}
    >
      {props.children}
    </button>
  );
}

function SelectOptionContainerImpl(props) {
  const { state, renderInline } = useContext(SelectContext);
  return state.isOpen || renderInline ? (
    <_SelectOptionContainer {...props} />
  ) : null;
}

function _SelectOptionContainer(props) {
  const {
    menuProps,
    state,
    renderInline,
    triggerRef,
    rootClassName,
  } = useContext(SelectContext);
  const ref = useRef(null);
  const { listBoxProps } = useListBox(
    {
      children: [],
      autoFocus: "first",
      disallowEmptySelection: true,
      "aria-label": exists(state.selectedKey) ? state.selectedKey : "none",
      id: menuProps.id,
    },
    state,
    ref
  );
  const gravityOffset = 10;
  const [buttonWidth, setButtonWidth] = useState(null);
  useLayoutEffect(() => {
    if (exists(triggerRef)) {
      const width = triggerRef.current.offsetWidth;
      setButtonWidth(width);
    }
  }, [triggerRef, state.selectedKey]);

  if (renderInline) {
    return (
      <ul
        ref={combineRef(ref, props.measureRef)}
        className={props.className}
        style={{
          marginTop: gravityOffset,
        }}
      >
        <ItemContext.Provider
          value={{
            isSelected: false,
            isFocused: false,
            key: null,
          }}
        >
          {props.children}
        </ItemContext.Provider>
      </ul>
    );
  }

  return (
    <Popover
      scrollRef={ref}
      triggerRef={triggerRef}
      isOpen={state.isOpen}
      containFocus
      onShouldClose={state.close}
      placement="bottom start"
    >
      <DismissButton onDismiss={() => state.close()} />
      <div key={props.innerKey} className={rootClassName}>
        {exists(props.cssStyles) ? (
          <style
            style={{
              display: "none",
            }}
          >
            {props.cssStyles}
          </style>
        ) : null}
        <ul
          {...mergeProps(listBoxProps, menuProps)}
          ref={combineRef(ref, props.measureRef)}
          className={props.className}
          style={{
            marginTop: gravityOffset,
            marginBottom: gravityOffset,
            overflow: "auto",
            ...(props.useButtonWidth
              ? {
                  width: buttonWidth,
                }
              : {}),
          }}
        >
          {[...state.collection].map((item) => (
            <Option key={item.key} item={item} state={state} />
          ))}
        </ul>
      </div>
      <DismissButton onDismiss={() => state.close()} />
    </Popover>
  );
}

function Option({ item, state }) {
  const ref = useRef();
  const isDisabled = state.disabledKeys.has(item.key);
  const isSelected = state.selectionManager.isSelected(item.key);
  const { optionProps } = useOption(
    {
      key: item.key,
      isDisabled,
      isSelected,
      shouldSelectOnPressUp: true,
      shouldFocusOnHover: true,
      "aria-label": item.key,
    },
    state,
    ref
  );
  const { focusProps, isFocusVisible } = useFocusRing();
  return (
    <li {...mergeProps(optionProps, focusProps)} ref={ref}>
      <ItemContext.Provider
        value={{
          isSelected,
          isFocused: isFocusVisible,
          key: item.key,
        }}
      >
        {item.rendered}
      </ItemContext.Provider>
    </li>
  );
}

export function SelectRootImpl(props) {
  const ref = useRef(null);
  const { selected, onSelect, renderInline, items } = props;
  const { style, testId, values, vislyProps, isDisabled } = usePrimitive({
    ref,
    props,
  });
  const { className, ...other } = vislyProps;
  const state = useSelectState({
    children: items,
    selectedKey: selected,
    onSelectionChange: onSelect,
    disallowEmptySelection: true,
    shouldFlip: true,
    label: "Select",
    isDisabled,
  });
  const { triggerProps, menuProps } = useSelect(
    {
      children: items,
      selectedKey: selected,
      onSelectionChange: onSelect,
      "aria-label": "Select",
      shouldFlip: true,
    },
    state,
    ref
  );
  triggerProps.isDisabled = isDisabled;
  return (
    <div
      className={className}
      style={{ ...style, display: renderInline ? "flex" : "contents" }}
    >
      <HiddenSelect
        state={state}
        triggerRef={ref}
        label="Select"
        name="Select"
      />
      <SelectContext.Provider
        value={{
          buttonStyles: style,
          renderInline,
          triggerProps,
          triggerRef: ref,
          triggerMeasureRef: props.measureRef,
          vislyProps: other,
          testId,
          state,
          menuProps,
          rootClassName: className,
        }}
      >
        {renderChildren(props.children, values)}
      </SelectContext.Provider>
    </div>
  );
}

function SelectOptionRootImpl(props) {
  const ref = useRef();
  const { isSelected, isFocused } = useContext(ItemContext) || {};
  const { style, testId, innerRef, values, vislyProps } = usePrimitive({
    ignoreFocusHandling: true,
    isFocusVisible: isFocused,
    ref,
    props,
    variants: isSelected
      ? [
          {
            propName: "selected",
          },
        ]
      : [],
  });
  return (
    <div
      key={props.value}
      ref={combineRef(props.measureRef, combineRef(innerRef, ref))}
      data-testid={testId}
      {...vislyProps}
      style={style}
    >
      {renderChildren(props.children, values)}
    </div>
  );
}

const ProxyElements = {
  Button: () => null,
  OptionContainer: (props) => {
    return <>{props.children}</>;
  },
};
export const SelectButton = proxy(ProxyElements.Button, SelectButtonImpl);
export const SelectOptionContainer = proxy(
  ProxyElements.OptionContainer,
  SelectOptionContainerImpl
);
export const SelectOptionRoot = proxy(
  CollectionItemProxy,
  SelectOptionRootImpl
);
export function SelectRoot(props) {
  return (
    <CollectionRoot
      {...props}
      ParentCtor={SelectRootImpl}
      ItemCtor={SelectOptionRootImpl}
    />
  );
}
