// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./Checkbox.css";
import React, { createContext, useContext } from "react";
import {
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { IconPrimitive } from "./_internal_primitives";
import { CheckboxRoot } from "./_internal_checkbox";

const styles = [
  {
    type: "default",
    layers: {
      checkmark: {
        none: {
          role: "img",
          src: require("../assets/5cd79169-4d72-486a-bd71-20cfa0420bb2@1x.svg"),
          useMask: true,
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "checked",
    layers: {
      checkmark: {
        none: {
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "checked",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "checked",
  },
];

export const CheckboxContext = createContext(null);

function Checkbox(_props) {
  const defaults = useContext(CheckboxContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <CheckboxRoot
      {...props}
      key="root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "root",
        scope: "WELyftQJp5",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <IconPrimitive
          className={"__visly_reset __visly_scope_WELyftQJp5_checkmark"}
          key={"checkmark"}
          useMask={getStyle("checkmark", "useMask")}
          src={getStyle("checkmark", "src")}
        />
      )}
    </CheckboxRoot>
  );
}

Checkbox.__variants = [
  {
    name: "checked",
    type: "variant",
  },
];

export default Checkbox;
