// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { IconPrimitive } from "./_internal_primitives";
import { CheckboxRoot } from "./_internal_checkbox";
import "./Checkbox.css";

const styles = [
  {
    type: "default",
    layers: {
      checkmark: {
        none: {
          role: "img",
          src: require("../assets/5cd79169-4d72-486a-bd71-20cfa0420bb2@1x.svg"),
          useMask: true,
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "checked",
    layers: {},
  },
];

export default function Checkbox(props) {
  return (
    <CheckboxRoot
      {...props}
      key="root"
      internal={{
        styles,
        layerId: "root",
        scope: "WELyftQJp5",
        variantPropTypes: [
          {
            type: "boolean",
            propName: "checked",
          },
        ],
      }}
    >
      {(getStyle) => (
        <IconPrimitive
          className={"__visly_reset __visly_checkmark __visly_scope_WELyftQJp5"}
          key={"checkmark"}
          useMask={getStyle("checkmark", "useMask")}
          src={getStyle("checkmark", "src")}
        />
      )}
    </CheckboxRoot>
  );
}
