// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists, getStyle } from "./_internal_utils";
import {
  StaticRootPrimitive,
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
  ProgressFillPrimitive,
} from "./_internal_primitives";
import { Root, InputPrimitive } from "./_internal_input";
import { CheckboxRoot } from "./_internal_checkbox";
import { ButtonRoot } from "./_internal_button";
import { TooltipRoot } from "./_internal_tooltip";
import { PopoverRoot } from "./_internal_popover";
import { DialogRoot, DialogContainerPrimitive } from "./_internal_dialog";
import { RadioGroupRoot, RadioGroupButtonRoot } from "./_internal_radio_group";
import "./Checkbox.css";
const styles = [
  {
    type: "default",
    layers: {
      checkmark: {
        none: {
          role: "img",
          src: require("../assets/5cd79169-4d72-486a-bd71-20cfa0420bb2@1x.svg"),
          useMask: true,
        },
      },
    },
  },
  { type: "boolean", propName: "checked", layers: {} },
];
export default function (props) {
  return (
    <CheckboxRoot
      {...{
        ...props,
        key: "root",
        internal: {
          styles,
          layerId: "root",
          scope: "ecb6005f-b9fc-4885-b1b9-d16023248ad3",
          variantPropTypes: [{ type: "boolean", propName: "checked" }],
        },
      }}
    >
      {(values) => [
        <IconPrimitive
          className={
            "__visly_reset __visly_checkmark __visly_scope_ecb6005f-b9fc-4885-b1b9-d16023248ad3"
          }
          key={"checkmark"}
          useMask={getStyle(values, "checkmark", "useMask")}
          src={getStyle(values, "checkmark", "src")}
        />,
      ]}
    </CheckboxRoot>
  );
}
