// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists } from "./_internal_utils";
import { IconPrimitive } from "./_internal_primitives";
import { ButtonRoot } from "./_internal_button";
import "./IconButton.css";

const styles = [
  {
    type: "default",
    layers: {
      UQGJpGfRHE: {
        none: {
          role: "img",
          src: require("../assets/154f1398-7a56-4c95-bd2d-6f436587fd18@1x.svg"),
          useMask: true,
        },
      },
    },
  },
];

export default function IconButton(props) {
  return (
    <ButtonRoot
      {...props}
      key="root"
      internal={{
        styles,
        layerId: "root",
        scope: "TVfnsEurhN",
        variantPropTypes: [],
      }}
    >
      {(getStyle) => (
        <IconPrimitive
          className={
            "__visly_reset __visly_UQGJpGfRHE __visly_scope_TVfnsEurhN"
          }
          key={"UQGJpGfRHE"}
          useMask={getStyle("UQGJpGfRHE", "useMask")}
          src={
            exists(props.icon)
              ? props.icon
              : require("../assets/154f1398-7a56-4c95-bd2d-6f436587fd18@1x.svg")
          }
        />
      )}
    </ButtonRoot>
  );
}
