// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists, selectStyle } from "./_internal_utils";
import {
  StaticRootPrimitive,
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
  ProgressFillPrimitive,
} from "./_internal_primitives";
import { Root, InputPrimitive } from "./_internal_input";
import { CheckboxRoot } from "./_internal_checkbox";
import { ButtonRoot } from "./_internal_button";
import { TooltipRoot } from "./_internal_tooltip";
import { SegmentedControlRoot } from "./_internal_segmented_control";
import { SegmentedControlButtonRoot } from "./_internal_segmented_control";
import "./IconButton.css";
const styles = [
  {
    type: "default",
    layers: {
      "dde648ad-9f39-4c14-bdd8-149aa61a1cb1": {
        none: {
          role: "img",
          src: require("../assets/5cd79169-4d72-486a-bd71-20cfa0420bb2@1x.svg"),
          useMask: true,
        },
      },
    },
  },
];
export default function (props) {
  return (
    <ButtonRoot
      {...{
        ...props,
        key: "root",
        internal: {
          styles,
          layerId: "root",
          scope: "d68e561e-25da-42bf-8396-a44e23d68742",
          variantPropTypes: [],
        },
      }}
    >
      {(values) => [
        <IconPrimitive
          className={
            "__visly_reset __visly_dde648ad-9f39-4c14-bdd8-149aa61a1cb1 __visly_scope_d68e561e-25da-42bf-8396-a44e23d68742"
          }
          key={"dde648ad-9f39-4c14-bdd8-149aa61a1cb1"}
          useMask={values["dde648ad-9f39-4c14-bdd8-149aa61a1cb1"]["useMask"]}
          src={
            exists(props.icon)
              ? props.icon
              : require("../assets/5cd79169-4d72-486a-bd71-20cfa0420bb2@1x.svg")
          }
        />,
      ]}
    </ButtonRoot>
  );
}
