// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./IconButton.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import { IconPrimitive } from "./_internal_primitives";
import { ButtonRoot } from "./_internal_button";

const styles = [
  {
    type: "default",
    layers: {
      UQGJpGfRHE: {
        none: {
          role: "img",
          src: require("../assets/154f1398-7a56-4c95-bd2d-6f436587fd18@1x.svg"),
          useMask: true,
        },
      },
    },
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
];

const variantPropTypes = [];

export const IconButtonContext = createContext(null);

function IconButton(_props) {
  const defaults = useContext(IconButtonContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <ButtonRoot
      {...props}
      key="root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "root",
        scope: "TVfnsEurhN",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <IconPrimitive
          className={"__visly_reset __visly_scope_TVfnsEurhN_UQGJpGfRHE"}
          key={"UQGJpGfRHE"}
          useMask={getStyle("UQGJpGfRHE", "useMask")}
          src={exists(props.icon) ? props.icon : getStyle("UQGJpGfRHE", "src")}
        />
      )}
    </ButtonRoot>
  );
}

IconButton.__variants = [];

export default IconButton;
