// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists } from "./_internal_utils";
import { Root, InputPrimitive } from "./_internal_input";
import "./Input.css";

const styles = [
  {
    type: "default",
    layers: {
      input: {
        none: {
          placeholderText: "Placeholder",
        },
      },
    },
  },
];

export default function Input(props) {
  return (
    <Root
      {...props}
      key="root"
      internal={{
        styles,
        layerId: "root",
        scope: "ABzyCKqm1K",
        variantPropTypes: [],
      }}
    >
      <InputPrimitive
        className={"__visly_reset __visly_input __visly_scope_ABzyCKqm1K"}
        key={"input"}
        placeholder={
          exists(props.placeholder) ? props.placeholder : "Placeholder"
        }
      />
    </Root>
  );
}
