// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists } from "./_internal_utils";
import { RadioGroupRoot } from "./_internal_radio_group";
import "./SegmentedControl.css";

const styles = [
  {
    type: "default",
    layers: {},
  },
];

export default function SegmentedControl(props) {
  return (
    <RadioGroupRoot
      {...{
        ...props,
        key: "segmented-control-root",
        addSpacing: false,
        internal: {
          styles,
          layerId: "segmented-control-root",
          scope: "segmented-control-root",
          variantPropTypes: [],
        },
      }}
    >
      {(getStyle) => [exists(props.children) ? props.children : null]}
    </RadioGroupRoot>
  );
}
