// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists, selectStyle } from "./_internal_utils";
import {
  StaticRootPrimitive,
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
  ProgressFillPrimitive,
} from "./_internal_primitives";
import { Root, InputPrimitive } from "./_internal_input";
import { CheckboxRoot } from "./_internal_checkbox";
import { ButtonRoot } from "./_internal_button";
import { TooltipRoot } from "./_internal_tooltip";
import { SegmentedControlRoot } from "./_internal_segmented_control";
import { SegmentedControlButtonRoot } from "./_internal_segmented_control";
import "./SegmentedControl.Button.css";
const styles = [
  {
    type: "default",
    layers: { "segmented-control-button-text": { none: { text: "Text" } } },
  },
  { type: "boolean", propName: "selected", layers: {} },
];
export default function (props) {
  return (
    <SegmentedControlButtonRoot
      {...{
        ...props,
        key: "segmented-control-button-root",
        internal: {
          styles,
          layerId: "segmented-control-button-root",
          scope: "63a98a57-7882-46c5-b56d-5e8a27e4deb5",
          variantPropTypes: [{ type: "boolean", propName: "selected" }],
        },
      }}
    >
      {(values) => [
        <TextPrimitive
          className={
            "__visly_reset __visly_segmented-control-button-text __visly_scope_63a98a57-7882-46c5-b56d-5e8a27e4deb5"
          }
          key={"segmented-control-button-text"}
          text={exists(props.text) ? props.text : "Text"}
        />,
      ]}
    </SegmentedControlButtonRoot>
  );
}
