// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists } from "./_internal_utils";
import { TextPrimitive } from "./_internal_primitives";
import { RadioGroupButtonRoot } from "./_internal_radio_group";
import "./SegmentedControl.Button.css";

const styles = [
  {
    type: "default",
    layers: {
      "segmented-control-button-text": {
        none: {
          text: "Text",
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "selected",
    layers: {},
  },
];

export default function Button(props) {
  return (
    <RadioGroupButtonRoot
      {...props}
      key="segmented-control-button-root"
      internal={{
        styles,
        layerId: "segmented-control-button-root",
        scope: "DJnp59Npst",
        variantPropTypes: [
          {
            type: "boolean",
            propName: "selected",
          },
        ],
      }}
    >
      <TextPrimitive
        className={
          "__visly_reset __visly_scope_DJnp59Npst_segmented-control-button-text"
        }
        key={"segmented-control-button-text"}
        text={exists(props.text) ? props.text : "Text"}
      />
    </RadioGroupButtonRoot>
  );
}
