// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists, selectStyle } from "./_internal_utils";
import {
  StaticRootPrimitive,
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
  ProgressFillPrimitive,
} from "./_internal_primitives";
import { Root, InputPrimitive } from "./_internal_input";
import { CheckboxRoot } from "./_internal_checkbox";
import { ButtonRoot } from "./_internal_button";
import { TooltipRoot } from "./_internal_tooltip";
import { SegmentedControlRoot } from "./_internal_segmented_control";
import { SegmentedControlButtonRoot } from "./_internal_segmented_control";
import "./SegmentedControl.css";
const styles = [{ type: "default", layers: {} }];
export default function (props) {
  return (
    <SegmentedControlRoot
      {...{
        ...props,
        key: "segmented-control-root",
        internal: {
          styles,
          layerId: "segmented-control-root",
          scope: "segmented-control-root",
          variantPropTypes: [],
        },
      }}
    >
      {(values) => [<>{exists(props.children) ? props.children : null}</>]}
    </SegmentedControlRoot>
  );
}
