// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import "./Select.css";
import React, { createContext, useContext } from "react";
import {
  exists,
  findSetVariantProps,
  makeCompositeDefaultProps,
} from "./_internal_utils";
import {
  SpacerPrimitive,
  TextPrimitive,
  IconPrimitive,
} from "./_internal_primitives";
import {
  SelectRoot,
  SelectOptionContainer,
  SelectButton,
} from "./_internal_select";

const styles = [
  {
    type: "default",
    layers: {
      "select-button-text": {
        none: {
          text: "Selected",
        },
      },
      NpW7qLp3hg: {
        none: {
          role: "img",
          src: require("../assets/c6f11592-eb2a-4697-9b7c-6c7c31b99f89@1x.svg"),
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "noShadow",
    layers: {},
  },
  {
    type: "boolean",
    propName: "customVariant",
    layers: {},
  },
];

const defaultPropValues = [
  {
    type: "default",
    layers: {},
  },
  {
    type: "boolean",
    propName: "noShadow",
    layers: {},
  },
  {
    type: "boolean",
    propName: "customVariant",
    layers: {},
  },
];

const variantPropTypes = [
  {
    type: "boolean",
    propName: "noShadow",
  },
  {
    type: "boolean",
    propName: "customVariant",
  },
];

export const SelectContext = createContext(null);

function Select(_props) {
  const defaults = useContext(SelectContext);
  const props = { ...defaults, ..._props };
  const activeVariants = findSetVariantProps(variantPropTypes, props);
  const getCompositeDefaultProps = makeCompositeDefaultProps(
    defaultPropValues,
    activeVariants
  );
  return (
    <SelectRoot
      {...props}
      key="select-root"
      addSpacing={false}
      internal={{
        styles: styles,
        layerId: "select-root",
        scope: "JSSaZPHiuy",
        activeVariants: activeVariants,
      }}
    >
      {(getStyle) => (
        <>
          <SelectButton
            key="select-button"
            className="__visly_reset __visly_scope_JSSaZPHiuy_select-button"
          >
            <TextPrimitive
              className={
                "__visly_reset __visly_scope_JSSaZPHiuy_select-button-text"
              }
              key={"select-button-text"}
              text={
                exists(props.label)
                  ? props.label
                  : getStyle("select-button-text", "text")
              }
            />
            <SpacerPrimitive
              className={"__visly_reset __visly_scope_JSSaZPHiuy_RmCK7Q7M2D"}
              key={"RmCK7Q7M2D"}
            />
            <IconPrimitive
              className={"__visly_reset __visly_scope_JSSaZPHiuy_NpW7qLp3hg"}
              key={"NpW7qLp3hg"}
              useMask={getStyle("NpW7qLp3hg", "useMask")}
              src={getStyle("NpW7qLp3hg", "src")}
            />
          </SelectButton>
          <SelectOptionContainer
            key="select-menu"
            className="__visly_reset __visly_scope_JSSaZPHiuy_select-menu"
            innerKey="select-menu"
            addSpacing={false}
            useButtonWidth={true}
          >
            {props.children}
          </SelectOptionContainer>
        </>
      )}
    </SelectRoot>
  );
}

Select.__variants = [
  {
    name: "noShadow",
    type: "variant",
  },
  {
    name: "customVariant",
    type: "variant",
  },
];

export default Select;
