// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists, getStyle } from "./_internal_utils";
import {
  StaticRootPrimitive,
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
  ProgressFillPrimitive,
} from "./_internal_primitives";
import { Root, InputPrimitive } from "./_internal_input";
import { CheckboxRoot } from "./_internal_checkbox";
import { ButtonRoot } from "./_internal_button";
import { TooltipRoot } from "./_internal_tooltip";
import { PopoverRoot } from "./_internal_popover";
import { DialogRoot, DialogContainerPrimitive } from "./_internal_dialog";
import { RadioGroupRoot, RadioGroupButtonRoot } from "./_internal_radio_group";
import "./SubmitInput.css";
const styles = [{ type: "default", layers: {} }];
import IconButton from "./IconButton";
import Input from "./Input";
export default function (props) {
  return (
    <RootPrimitive
      {...{
        ...props,
        key: "c432a5c1-ce27-4fbf-a6f7-0e44ccaa7823",
        internal: {
          styles,
          layerId: "c432a5c1-ce27-4fbf-a6f7-0e44ccaa7823",
          scope: "b63b42cb-4c3a-43e4-a0e9-96a1db328612",
          variantPropTypes: [],
        },
        addSpacing: false,
      }}
    >
      {(values) => [
        <Input
          key={"f280b223-c158-470e-bb18-ababbb5f927c"}
          {...{
            placeholder: props["placeholder"],
            value: props["value"],
            onChange: props["onChange"],
            className:
              "__visly_reset __visly_f280b223-c158-470e-bb18-ababbb5f927c __visly_scope_b63b42cb-4c3a-43e4-a0e9-96a1db328612",
          }}
        />,
        <ContainerPrimitive
          className={
            "__visly_reset __visly_ac02595e-1d06-4529-b628-4ef7ffe9e60f __visly_scope_b63b42cb-4c3a-43e4-a0e9-96a1db328612"
          }
          key={"ac02595e-1d06-4529-b628-4ef7ffe9e60f"}
          addSpacing={false}
        >
          {[
            <IconButton
              key={"5d47a71f-ff3c-4836-b92a-319a91ff1743"}
              {...{
                icon: require("../assets/154f1398-7a56-4c95-bd2d-6f436587fd18@1x.svg"),
                onClick: props["onSubmit"],
                className:
                  "__visly_reset __visly_5d47a71f-ff3c-4836-b92a-319a91ff1743 __visly_scope_b63b42cb-4c3a-43e4-a0e9-96a1db328612",
              }}
            />,
          ]}
        </ContainerPrimitive>,
      ]}
    </RootPrimitive>
  );
}
