// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists } from "./_internal_utils";
import {
  RootPrimitive,
  SpacerPrimitive,
  TextPrimitive,
  ContainerPrimitive,
} from "./_internal_primitives";
import "./Task.css";
import Checkbox from "./Checkbox";

const styles = [
  {
    type: "default",
    layers: {
      DksnnuLiou: {
        none: {
          text: "01/01/2020 15:22",
        },
      },
      PJCCtmZ9Ea: {
        none: {
          text: "This is a task that needs to get done",
        },
      },
    },
  },
  {
    type: "boolean",
    propName: "done",
    layers: {},
  },
];

export default function Task(props) {
  return (
    <RootPrimitive
      {...props}
      key="24TAp68qmf"
      internal={{
        styles,
        layerId: "24TAp68qmf",
        scope: "uBZih7sxcZ",
        variantPropTypes: [
          {
            type: "boolean",
            propName: "done",
          },
        ],
      }}
      addSpacing={false}
    >
      <ContainerPrimitive
        className={"__visly_reset __visly_scope_uBZih7sxcZ_Ut44Zfa3Po"}
        key={"Ut44Zfa3Po"}
        addSpacing={false}
      >
        <TextPrimitive
          className={"__visly_reset __visly_scope_uBZih7sxcZ_PJCCtmZ9Ea"}
          key={"PJCCtmZ9Ea"}
          text={
            exists(props.title)
              ? props.title
              : "This is a task that needs to get done"
          }
        />
        <SpacerPrimitive
          className={"__visly_reset __visly_scope_uBZih7sxcZ_FMiM7kukGw"}
          key={"FMiM7kukGw"}
        />
        <TextPrimitive
          className={"__visly_reset __visly_scope_uBZih7sxcZ_DksnnuLiou"}
          key={"DksnnuLiou"}
          text={exists(props.date) ? props.date : "01/01/2020 15:22"}
        />
      </ContainerPrimitive>
      <SpacerPrimitive
        className={"__visly_reset __visly_scope_uBZih7sxcZ_L3WNqdT8hE"}
        key={"L3WNqdT8hE"}
      />
      <Checkbox
        key={"RswroRuchz"}
        {...{
          onChange: props["onCheckedChanged"],
          checked: props["checked"],
          className: "__visly_reset __visly_scope_uBZih7sxcZ_RswroRuchz",
        }}
      />
    </RootPrimitive>
  );
}
