// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists, getStyle } from "./_internal_utils";
import {
  StaticRootPrimitive,
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
  ProgressFillPrimitive,
} from "./_internal_primitives";
import { Root, InputPrimitive } from "./_internal_input";
import { CheckboxRoot } from "./_internal_checkbox";
import { ButtonRoot } from "./_internal_button";
import { TooltipRoot } from "./_internal_tooltip";
import { PopoverRoot } from "./_internal_popover";
import { DialogRoot, DialogContainerPrimitive } from "./_internal_dialog";
import { RadioGroupRoot, RadioGroupButtonRoot } from "./_internal_radio_group";
import "./Task.css";
const styles = [
  {
    type: "default",
    layers: {
      "674df238-9430-4604-93c4-ecc687537eb2": {
        none: { text: "01/01/2020 15:22" },
      },
      "b48f9997-3553-4eda-9fe6-ce42c627fbf6": {
        none: { text: "This is a task that needs to get done" },
      },
    },
  },
  { type: "boolean", propName: "done", layers: {} },
];
import Checkbox from "./Checkbox";
export default function (props) {
  return (
    <RootPrimitive
      {...{
        ...props,
        key: "08947f4e-ab23-4154-a81c-a841cfdbb060",
        internal: {
          styles,
          layerId: "08947f4e-ab23-4154-a81c-a841cfdbb060",
          scope: "07492fb8-7ca3-49dc-bb25-e81553625bc0",
          variantPropTypes: [{ type: "boolean", propName: "done" }],
        },
        addSpacing: false,
      }}
    >
      {(values) => [
        <ContainerPrimitive
          className={
            "__visly_reset __visly_e1c79011-686b-4984-8afc-026e3f7fc5c3 __visly_scope_07492fb8-7ca3-49dc-bb25-e81553625bc0"
          }
          key={"e1c79011-686b-4984-8afc-026e3f7fc5c3"}
          addSpacing={false}
        >
          {[
            <TextPrimitive
              className={
                "__visly_reset __visly_b48f9997-3553-4eda-9fe6-ce42c627fbf6 __visly_scope_07492fb8-7ca3-49dc-bb25-e81553625bc0"
              }
              key={"b48f9997-3553-4eda-9fe6-ce42c627fbf6"}
              text={
                exists(props.title)
                  ? props.title
                  : "This is a task that needs to get done"
              }
            />,
            <SpacerPrimitive
              className={
                "__visly_reset __visly_74444c2b-1fc5-499c-a865-749bf034585d __visly_scope_07492fb8-7ca3-49dc-bb25-e81553625bc0"
              }
              key={"74444c2b-1fc5-499c-a865-749bf034585d"}
            />,
            <TextPrimitive
              className={
                "__visly_reset __visly_674df238-9430-4604-93c4-ecc687537eb2 __visly_scope_07492fb8-7ca3-49dc-bb25-e81553625bc0"
              }
              key={"674df238-9430-4604-93c4-ecc687537eb2"}
              text={exists(props.date) ? props.date : "01/01/2020 15:22"}
            />,
          ]}
        </ContainerPrimitive>,
        <SpacerPrimitive
          className={
            "__visly_reset __visly_02a8ad22-ae8d-4231-b163-9533d272aa0c __visly_scope_07492fb8-7ca3-49dc-bb25-e81553625bc0"
          }
          key={"02a8ad22-ae8d-4231-b163-9533d272aa0c"}
        />,
        <Checkbox
          key={"c97852fc-e491-48c6-8227-502b71f0a35f"}
          {...{
            onChange: props["onCheckedChanged"],
            checked: props["checked"],
            className:
              "__visly_reset __visly_c97852fc-e491-48c6-8227-502b71f0a35f __visly_scope_07492fb8-7ca3-49dc-bb25-e81553625bc0",
          }}
        />,
      ]}
    </RootPrimitive>
  );
}
