// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
import "../textstyles/fonts.css";
import "./reset.css";
import React from "react";
import { exists, selectStyle } from "./_internal_utils";
import {
  StaticRootPrimitive,
  RootPrimitive,
  SpacerPrimitive,
  ImagePrimitive,
  TextPrimitive,
  ContainerPrimitive,
  IconPrimitive,
  ProgressFillPrimitive,
} from "./_internal_primitives";
import { Root, InputPrimitive } from "./_internal_input";
import { CheckboxRoot } from "./_internal_checkbox";
import { ButtonRoot } from "./_internal_button";
import { TooltipRoot } from "./_internal_tooltip";
import { SegmentedControlRoot } from "./_internal_segmented_control";
import { SegmentedControlButtonRoot } from "./_internal_segmented_control";
import "./Tooltip.css";
const styles = [
  {
    type: "default",
    layers: {
      "d6372cb3-7255-4394-9c75-9f8f7f08f587": {
        none: { arrowColor: "rgba(0,0,0,1)" },
      },
      "tooltip-text": { none: { text: "Tooltip" } },
    },
  },
];
export default function (props) {
  return (
    <TooltipRoot
      {...{
        ...props,
        key: "d6372cb3-7255-4394-9c75-9f8f7f08f587",
        internal: {
          styles,
          layerId: "d6372cb3-7255-4394-9c75-9f8f7f08f587",
          scope: "5d018349-0995-4ed4-b343-ac257591bcb5",
          variantPropTypes: [],
        },
        internalChildren: (values) => [
          <TextPrimitive
            className={
              "__visly_reset __visly_tooltip-text __visly_scope_5d018349-0995-4ed4-b343-ac257591bcb5"
            }
            key={"tooltip-text"}
            text={exists(props.text) ? props.text : "Tooltip"}
          />,
        ],
      }}
    >
      {props.children}
    </TooltipRoot>
  );
}
