// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const color: {
  success: "7fe804fc-6703-459a-877b-fcb6014a3404";
  successDark: "e9eaba7e-6f03-4da5-89be-a1b3189f1c74";
  danger: "11b50bf5-7fc3-49fd-be3f-55630e160227";
  dangerDark: "155a159e-6355-4c85-9ddc-8907e3ce6e00";
  dangerLight: "ec5a898e-e883-4fe6-8cc3-f1b42b895d7f";
  purple: "9fc962f7-8663-41ce-a800-2f12b7085ac4";
  purpleLight: "b0bf0b82-1078-4209-8c08-f45554334469";
  purpleDark: "35e723c6-d823-4e03-af99-da3e631110cc";
  yellow: "2f04ab61-1085-45a9-80ef-0e96d615af40";
  green: "7d57139b-4ba1-46c2-9250-c3a03b37d7de";
  red: "dd0bf2a4-3ee8-4abb-ad4a-7a76bf0ea362";
  vislyWhite: "5d23211a48a58b00174a6e84";
  vislyBlack: "016f62fe-6768-4643-a1de-3437bf7844fe";
  vislyBlue: "c582e7a8-5be2-4a3c-bbb2-3a491374aee0";
  vislyBlueDark: "a2a6e934-51e9-460f-9d8f-bbdbe30d7f01";
  vislyGrayLight: "4904d7db-87c7-4dc9-881f-df8fc83be0dc";
  vislyGray: "e06d6332-aae6-4578-87f3-cadf0bf47819";
  vislyGrayDark: "5985ed98-a56f-4176-9f20-431309b7e9dc";
  vislyBlueLight: "8e0442b4-542a-47a8-9b75-979a6fa5a174";
};
export const icon: {
  arrowDown: "c6bc9d44-be23-423b-b21e-2a46b497715b";
  arrowRight: "03d4c975-6eb4-4936-b715-550ca471fb50";
  arrowLeft: "1e8b12ac-a30a-4fc0-9f73-d91668b19e7b";
  help: "3cf6b9cd-8891-4614-a9fb-4e60a6518d8d";
  arrowUp: "1c3cf134-847d-4c39-952b-1adfadee70a1";
  info: "e70bbf68-106c-4134-9b05-40747df21168";
  mail: "ddb4f971-e1cd-4719-a639-2484f058c658";
  more: "5fe81eb8-ce0b-4036-a5a9-d5ef20ae3262";
  menu: "1c9f5244-d8e1-4cf6-b35b-c38d76e56dc9";
  search: "e19d5b73-20f3-47fb-ae50-a07dcf6129a6";
  trash: "4e3cc665-52b4-471a-b6b5-b8378fdbf2fe";
  user: "be4457dc-7e13-4ec5-bf0e-6a31b7351216";
  close: "00b0df88-4f54-4044-8217-261b49cbe480";
  upload: "747aa4b2-4a9c-4576-bfc1-eef45de8d44f";
  plus: "e3925900-8edf-4dde-8a06-ae30b42f3cef";
  vislyCheck: "567b267e-ef5e-4078-b042-d5c96e513048";
  vislyRadioBorder: "d0171f72-9dbe-4e54-b469-a4432d2beca6";
  vislyRadioCenter: "22ef53ca-3265-49f9-85f5-c00ff038c977";
  vislySelect: "562e1b22-bb85-483b-b4a0-52c23363fef5";
};
export const font: {
  "Whyte-Bold": "1a10a760-7a92-490f-9124-407664655a9a";
  "Inter-SemiBold": "738a7887-09d7-4152-ba19-bd39b48d602d";
  "Inter-Regular": "e975e34d-eef1-48e6-92b1-58f5aa6c2449";
  "Inter-Medium": "59755b9e-24c5-4bdf-917b-e9a1f16ebb82";
  "Whyte-Regular": "892705e8-aeb9-4573-87af-ede8cdef7868";
  "Roboto-Bold": "d7d2c5b4-4c7b-4efb-9c21-0ef70f800be8";
  "Roboto-Medium": "925b1f14-e32f-4af1-b2ee-80132fd73b20";
  "Roboto-Regular": "c775fc02-e85e-4e5f-b67a-b62e4ed19fb9";
};
export const textstyle: {
  headingLarge: "5da5cac4cfe5e80058716999";
  heading: "5da5caf0cfe5e800587169b1";
  headingSmall: "5da5cb0bcfe5e800587169cb";
  label: "8365cb6a-9d1e-4974-93ae-fd8c6a8212f0";
  labelSmall: "66344487-ae24-412f-a5f9-67bb22a48424";
  vislyLabel: "5da5cba2cfe5e80058716a47";
  vislyLabelSmall: "053633e0-982d-4d5a-8df3-b08680e7389c";
};
export const component: {
  ProgressBar: "b9eb7797-248a-47c6-809a-35ba3ed55557";
  Tooltip: "5d018349-0995-4ed4-b343-ac257591bcb5";
  Input: "4a6b6905-154a-43b4-a97a-e8e8ae9fa6e0";
  Button: "e15d6bca-c0c9-4ab0-b856-12d569ad0524";
  Checkbox: "ecb6005f-b9fc-4885-b1b9-d16023248ad3";
  IconButton: "d68e561e-25da-42bf-8396-a44e23d68742";
  Task: "07492fb8-7ca3-49dc-bb25-e81553625bc0";
  SubmitInput: "b63b42cb-4c3a-43e4-a0e9-96a1db328612";
  Page: "c00dfc9b-d69d-4a89-8df3-6abf3756275b";
  SegmentedControl: "664bf8eb-f8b1-43e9-bf0f-f541cb9f961a";
};
