// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const color: {
  backgroundGray: "92d07223-c5b7-44da-abed-07af9b86e57d";
  baseDark: "6f64237e-a096-4fb0-a1d7-5ea6b6461418";
  baseDisabled: "d94ef886-8fc6-45d3-bfb6-4467d58a1161";
  danger: "11b50bf5-7fc3-49fd-be3f-55630e160227";
  dangerDark: "155a159e-6355-4c85-9ddc-8907e3ce6e00";
  dangerLight: "ec5a898e-e883-4fe6-8cc3-f1b42b895d7f";
  focusHighlight: "3effbc42-e898-4afc-ac0a-7dbaa3cfd645";
  green: "7d57139b-4ba1-46c2-9250-c3a03b37d7de";
  grey: "3d7cd3fa-18a2-4407-9d65-fd807d01d2a0";
  purple: "afedd554-d84d-49f4-9799-6cd6c392cdab";
  purpleLight: "b0bf0b82-1078-4209-8c08-f45554334469";
  red: "dd0bf2a4-3ee8-4abb-ad4a-7a76bf0ea362";
  success: "7fe804fc-6703-459a-877b-fcb6014a3404";
  successDark: "e9eaba7e-6f03-4da5-89be-a1b3189f1c74";
  white: "70e5e0d5-0ae3-4aa3-8581-b9a45d79c57a";
  yellow: "2f04ab61-1085-45a9-80ef-0e96d615af40";
};
export const icon: {
  arrowDown: "c6bc9d44-be23-423b-b21e-2a46b497715b";
  arrowLeft: "1e8b12ac-a30a-4fc0-9f73-d91668b19e7b";
  arrowRight: "03d4c975-6eb4-4936-b715-550ca471fb50";
  arrowUp: "1c3cf134-847d-4c39-952b-1adfadee70a1";
  close: "00b0df88-4f54-4044-8217-261b49cbe480";
  help: "3cf6b9cd-8891-4614-a9fb-4e60a6518d8d";
  info: "e70bbf68-106c-4134-9b05-40747df21168";
  mail: "ddb4f971-e1cd-4719-a639-2484f058c658";
  menu: "1c9f5244-d8e1-4cf6-b35b-c38d76e56dc9";
  more: "5fe81eb8-ce0b-4036-a5a9-d5ef20ae3262";
  plus: "e3925900-8edf-4dde-8a06-ae30b42f3cef";
  search: "e19d5b73-20f3-47fb-ae50-a07dcf6129a6";
  trash: "4e3cc665-52b4-471a-b6b5-b8378fdbf2fe";
  upload: "747aa4b2-4a9c-4576-bfc1-eef45de8d44f";
  user: "be4457dc-7e13-4ec5-bf0e-6a31b7351216";
  vislyCheck: "567b267e-ef5e-4078-b042-d5c96e513048";
  vislyRadioBorder: "d0171f72-9dbe-4e54-b469-a4432d2beca6";
  vislyRadioCenter: "22ef53ca-3265-49f9-85f5-c00ff038c977";
  vislySelect: "562e1b22-bb85-483b-b4a0-52c23363fef5";
};
export const font: {
  "Whyte-Bold": "1a10a760-7a92-490f-9124-407664655a9a";
  "Inter-SemiBold": "fe6f3a02-ee87-443a-ace7-167a9af185cd";
  "Inter-Regular": "b0c0f064-81be-4383-993f-74528150ee81";
  "Inter-Medium": "a0752896-a456-40db-82df-44418f8af538";
  "Whyte-Regular": "892705e8-aeb9-4573-87af-ede8cdef7868";
  "Roboto-Bold": "d7d2c5b4-4c7b-4efb-9c21-0ef70f800be8";
  "Roboto-Medium": "925b1f14-e32f-4af1-b2ee-80132fd73b20";
  "Roboto-Regular": "c775fc02-e85e-4e5f-b67a-b62e4ed19fb9";
  "Inter-Black": "2db51490-ce4e-4db8-9f10-4d0b24a059de";
  "Inter-BlackItalic": "82812a09-0fa5-4251-bc27-e9b0af32b813";
  "Inter-ExtraBold": "0c9a5879-0e21-4227-b2bc-99d300e43e52";
  "Inter-Bold": "7a7256d5-465e-4420-a713-c96bce455d8c";
  "Inter-BoldItalic": "652b3044-fc52-4daf-8ed6-c23f6b0696e2";
  "Inter-ExtraBoldItalic": "12e1b958-3c86-4f4b-b1ad-7ac1b470f79c";
  "Inter-ExtraLightItalic": "2348ce05-0aeb-44d2-8088-470a369c3121";
  "Inter-ExtraLight": "15503404-0609-41aa-b496-1b37912fe091";
  "Inter-Light": "fc164fb1-451b-44f0-a41b-f73111ffa6c4";
  "Inter-Italic": "d17dabe0-5132-4fb3-beae-0d01d1759f7a";
  "Inter-LightItalic": "bde81d66-a8fe-4215-be53-f48510d21785";
  "Inter-MediumItalic": "ac425dad-6034-476b-973f-b77153d3f0a8";
  "Inter-SemiBoldItalic": "47fa28fd-8c21-4716-b4ff-5338824b33ef";
  "Inter-ThinItalic": "485e0fcf-ba64-4390-b6d0-92057cc52529";
  "Inter-Thin": "f8cd0728-b297-4161-94c2-5ba185d1e09a";
};
export const textstyle: {
  heading: "5da5caf0cfe5e800587169b1";
  headingLarge: "5da5cac4cfe5e80058716999";
  headingSmall: "5da5cb0bcfe5e800587169cb";
  label: "8365cb6a-9d1e-4974-93ae-fd8c6a8212f0";
  labelSmall: "66344487-ae24-412f-a5f9-67bb22a48424";
};
export const size: {};
export const shadow: {
  uhjgbkjhgjkh: "b332f851-7eb6-446d-86c6-e3dca23e7278";
};
export const component: {
  Button: "e15d6bca-c0c9-4ab0-b856-12d569ad0524";
  Checkbox: "ecb6005f-b9fc-4885-b1b9-d16023248ad3";
  IconButton: "d68e561e-25da-42bf-8396-a44e23d68742";
  Input: "4a6b6905-154a-43b4-a97a-e8e8ae9fa6e0";
  List: "3b7716d9-f354-42a8-b7d4-e9472424853d";
  Page: "c00dfc9b-d69d-4a89-8df3-6abf3756275b";
  ProgressBar: "b9eb7797-248a-47c6-809a-35ba3ed55557";
  SegmentedControl: "664bf8eb-f8b1-43e9-bf0f-f541cb9f961a";
  Select: "8d38b6ff-94cc-4a6f-8ea1-cee041f1e171";
  ShadowTesting: "92293685-f433-4a6f-adb8-03d1d8f47229";
  SubmitInput: "b63b42cb-4c3a-43e4-a0e9-96a1db328612";
  Task: "07492fb8-7ca3-49dc-bb25-e81553625bc0";
  Tooltip: "5d018349-0995-4ed4-b343-ac257591bcb5";
};
