// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* tslint:disable */
/* eslint-disable */
export const arrowDown: string;
export const arrowLeft: string;
export const arrowRight: string;
export const arrowUp: string;
export const close: string;
export const help: string;
export const info: string;
export const mail: string;
export const menu: string;
export const more: string;
export const plus: string;
export const search: string;
export const trash: string;
export const upload: string;
export const user: string;
export const vislyCheck: string;
export const vislyRadioBorder: string;
export const vislyRadioCenter: string;
export const vislySelect: string;
